#!/bin/bash
# Simple build script, potentially useful if building a GPL-redistributable
# version on a system *without* SPEC CPU2017.  See:
#
#     https://www.spec.org/cpu2017/Docs/licenses.html#GPLtarballs
#
# Note: if the benchmark uses "specpp", that is the freely-redistributable
#       preprocessor "filepp".   It is described at 
#         https://www.spec.org/cpu2017/Docs/utility.html#specpp  
#       and will need to be in your path.  You can find filepp sources as
#       modified by SPEC in redistributable_sources/modified/tools.src/harness-spec.tar.xz 
#---------------------------------------------------------------------------

# Added `-std=c++14` to the compile command to fix the following error:
# error: ISO C++17 does not allow 'register' storage class specifier

/home/yjs/workspace/GPUISel-llvm/build/bin/clang++ -O3 -S -emit-llvm -funroll-loops -mllvm -force-vector-interleave=4 -fvectorize -std=c++14                -m64 -c -o atmosph.ll -DSPEC -DSPEC_CPU -DNDEBUG -Ifrontend -Ibase -I. -Ispec_qsort -DSPEC_AUTO_SUPPRESS_OPENMP         -DSPEC_LP64  atmosph.cpp
/home/yjs/workspace/GPUISel-llvm/build/bin/clang++ -O3 -S -emit-llvm -funroll-loops -mllvm -force-vector-interleave=4 -fvectorize -std=c++14                -m64 -c -o bbox.ll -DSPEC -DSPEC_CPU -DNDEBUG -Ifrontend -Ibase -I. -Ispec_qsort -DSPEC_AUTO_SUPPRESS_OPENMP         -DSPEC_LP64  bbox.cpp
/home/yjs/workspace/GPUISel-llvm/build/bin/clang++ -O3 -S -emit-llvm -funroll-loops -mllvm -force-vector-interleave=4 -fvectorize -std=c++14                -m64 -c -o bcyl.ll -DSPEC -DSPEC_CPU -DNDEBUG -Ifrontend -Ibase -I. -Ispec_qsort -DSPEC_AUTO_SUPPRESS_OPENMP         -DSPEC_LP64  bcyl.cpp
/home/yjs/workspace/GPUISel-llvm/build/bin/clang++ -O3 -S -emit-llvm -funroll-loops -mllvm -force-vector-interleave=4 -fvectorize -std=c++14                -m64 -c -o benchmark.ll -DSPEC -DSPEC_CPU -DNDEBUG -Ifrontend -Ibase -I. -Ispec_qsort -DSPEC_AUTO_SUPPRESS_OPENMP         -DSPEC_LP64  benchmark.cpp
/home/yjs/workspace/GPUISel-llvm/build/bin/clang++ -O3 -S -emit-llvm -funroll-loops -mllvm -force-vector-interleave=4 -fvectorize -std=c++14                -m64 -c -o bezier.ll -DSPEC -DSPEC_CPU -DNDEBUG -Ifrontend -Ibase -I. -Ispec_qsort -DSPEC_AUTO_SUPPRESS_OPENMP         -DSPEC_LP64  bezier.cpp
/home/yjs/workspace/GPUISel-llvm/build/bin/clang++ -O3 -S -emit-llvm -funroll-loops -mllvm -force-vector-interleave=4 -fvectorize -std=c++14                -m64 -c -o blob.ll -DSPEC -DSPEC_CPU -DNDEBUG -Ifrontend -Ibase -I. -Ispec_qsort -DSPEC_AUTO_SUPPRESS_OPENMP         -DSPEC_LP64  blob.cpp
/home/yjs/workspace/GPUISel-llvm/build/bin/clang++ -O3 -S -emit-llvm -funroll-loops -mllvm -force-vector-interleave=4 -fvectorize -std=c++14                -m64 -c -o boxes.ll -DSPEC -DSPEC_CPU -DNDEBUG -Ifrontend -Ibase -I. -Ispec_qsort -DSPEC_AUTO_SUPPRESS_OPENMP         -DSPEC_LP64  boxes.cpp
/home/yjs/workspace/GPUISel-llvm/build/bin/clang++ -O3 -S -emit-llvm -funroll-loops -mllvm -force-vector-interleave=4 -fvectorize -std=c++14                -m64 -c -o bsphere.ll -DSPEC -DSPEC_CPU -DNDEBUG -Ifrontend -Ibase -I. -Ispec_qsort -DSPEC_AUTO_SUPPRESS_OPENMP         -DSPEC_LP64  bsphere.cpp
/home/yjs/workspace/GPUISel-llvm/build/bin/clang++ -O3 -S -emit-llvm -funroll-loops -mllvm -force-vector-interleave=4 -fvectorize -std=c++14                -m64 -c -o camera.ll -DSPEC -DSPEC_CPU -DNDEBUG -Ifrontend -Ibase -I. -Ispec_qsort -DSPEC_AUTO_SUPPRESS_OPENMP         -DSPEC_LP64  camera.cpp
/home/yjs/workspace/GPUISel-llvm/build/bin/clang++ -O3 -S -emit-llvm -funroll-loops -mllvm -force-vector-interleave=4 -fvectorize -std=c++14                -m64 -c -o chi2.ll -DSPEC -DSPEC_CPU -DNDEBUG -Ifrontend -Ibase -I. -Ispec_qsort -DSPEC_AUTO_SUPPRESS_OPENMP         -DSPEC_LP64  chi2.cpp
/home/yjs/workspace/GPUISel-llvm/build/bin/clang++ -O3 -S -emit-llvm -funroll-loops -mllvm -force-vector-interleave=4 -fvectorize -std=c++14                -m64 -c -o colour.ll -DSPEC -DSPEC_CPU -DNDEBUG -Ifrontend -Ibase -I. -Ispec_qsort -DSPEC_AUTO_SUPPRESS_OPENMP         -DSPEC_LP64  colour.cpp
/home/yjs/workspace/GPUISel-llvm/build/bin/clang++ -O3 -S -emit-llvm -funroll-loops -mllvm -force-vector-interleave=4 -fvectorize -std=c++14                -m64 -c -o colutils.ll -DSPEC -DSPEC_CPU -DNDEBUG -Ifrontend -Ibase -I. -Ispec_qsort -DSPEC_AUTO_SUPPRESS_OPENMP         -DSPEC_LP64  colutils.cpp
/home/yjs/workspace/GPUISel-llvm/build/bin/clang++ -O3 -S -emit-llvm -funroll-loops -mllvm -force-vector-interleave=4 -fvectorize -std=c++14                -m64 -c -o cones.ll -DSPEC -DSPEC_CPU -DNDEBUG -Ifrontend -Ibase -I. -Ispec_qsort -DSPEC_AUTO_SUPPRESS_OPENMP         -DSPEC_LP64  cones.cpp
/home/yjs/workspace/GPUISel-llvm/build/bin/clang++ -O3 -S -emit-llvm -funroll-loops -mllvm -force-vector-interleave=4 -fvectorize -std=c++14                -m64 -c -o csg.ll -DSPEC -DSPEC_CPU -DNDEBUG -Ifrontend -Ibase -I. -Ispec_qsort -DSPEC_AUTO_SUPPRESS_OPENMP         -DSPEC_LP64  csg.cpp
/home/yjs/workspace/GPUISel-llvm/build/bin/clang++ -O3 -S -emit-llvm -funroll-loops -mllvm -force-vector-interleave=4 -fvectorize -std=c++14                -m64 -c -o discs.ll -DSPEC -DSPEC_CPU -DNDEBUG -Ifrontend -Ibase -I. -Ispec_qsort -DSPEC_AUTO_SUPPRESS_OPENMP         -DSPEC_LP64  discs.cpp
/home/yjs/workspace/GPUISel-llvm/build/bin/clang++ -O3 -S -emit-llvm -funroll-loops -mllvm -force-vector-interleave=4 -fvectorize -std=c++14                -m64 -c -o express.ll -DSPEC -DSPEC_CPU -DNDEBUG -Ifrontend -Ibase -I. -Ispec_qsort -DSPEC_AUTO_SUPPRESS_OPENMP         -DSPEC_LP64  express.cpp
/home/yjs/workspace/GPUISel-llvm/build/bin/clang++ -O3 -S -emit-llvm -funroll-loops -mllvm -force-vector-interleave=4 -fvectorize -std=c++14                -m64 -c -o fncode.ll -DSPEC -DSPEC_CPU -DNDEBUG -Ifrontend -Ibase -I. -Ispec_qsort -DSPEC_AUTO_SUPPRESS_OPENMP         -DSPEC_LP64  fncode.cpp
/home/yjs/workspace/GPUISel-llvm/build/bin/clang++ -O3 -S -emit-llvm -funroll-loops -mllvm -force-vector-interleave=4 -fvectorize -std=c++14                -m64 -c -o fnintern.ll -DSPEC -DSPEC_CPU -DNDEBUG -Ifrontend -Ibase -I. -Ispec_qsort -DSPEC_AUTO_SUPPRESS_OPENMP         -DSPEC_LP64  fnintern.cpp
/home/yjs/workspace/GPUISel-llvm/build/bin/clang++ -O3 -S -emit-llvm -funroll-loops -mllvm -force-vector-interleave=4 -fvectorize -std=c++14                -m64 -c -o fnpovfpu.ll -DSPEC -DSPEC_CPU -DNDEBUG -Ifrontend -Ibase -I. -Ispec_qsort -DSPEC_AUTO_SUPPRESS_OPENMP         -DSPEC_LP64  fnpovfpu.cpp
/home/yjs/workspace/GPUISel-llvm/build/bin/clang++ -O3 -S -emit-llvm -funroll-loops -mllvm -force-vector-interleave=4 -fvectorize -std=c++14                -m64 -c -o fnsyntax.ll -DSPEC -DSPEC_CPU -DNDEBUG -Ifrontend -Ibase -I. -Ispec_qsort -DSPEC_AUTO_SUPPRESS_OPENMP         -DSPEC_LP64  fnsyntax.cpp
/home/yjs/workspace/GPUISel-llvm/build/bin/clang++ -O3 -S -emit-llvm -funroll-loops -mllvm -force-vector-interleave=4 -fvectorize -std=c++14                -m64 -c -o fpmetric.ll -DSPEC -DSPEC_CPU -DNDEBUG -Ifrontend -Ibase -I. -Ispec_qsort -DSPEC_AUTO_SUPPRESS_OPENMP         -DSPEC_LP64  fpmetric.cpp
/home/yjs/workspace/GPUISel-llvm/build/bin/clang++ -O3 -S -emit-llvm -funroll-loops -mllvm -force-vector-interleave=4 -fvectorize -std=c++14                -m64 -c -o fractal.ll -DSPEC -DSPEC_CPU -DNDEBUG -Ifrontend -Ibase -I. -Ispec_qsort -DSPEC_AUTO_SUPPRESS_OPENMP         -DSPEC_LP64  fractal.cpp
/home/yjs/workspace/GPUISel-llvm/build/bin/clang++ -O3 -S -emit-llvm -funroll-loops -mllvm -force-vector-interleave=4 -fvectorize -std=c++14                -m64 -c -o function.ll -DSPEC -DSPEC_CPU -DNDEBUG -Ifrontend -Ibase -I. -Ispec_qsort -DSPEC_AUTO_SUPPRESS_OPENMP         -DSPEC_LP64  function.cpp
/home/yjs/workspace/GPUISel-llvm/build/bin/clang++ -O3 -S -emit-llvm -funroll-loops -mllvm -force-vector-interleave=4 -fvectorize -std=c++14                -m64 -c -o hcmplx.ll -DSPEC -DSPEC_CPU -DNDEBUG -Ifrontend -Ibase -I. -Ispec_qsort -DSPEC_AUTO_SUPPRESS_OPENMP         -DSPEC_LP64  hcmplx.cpp
/home/yjs/workspace/GPUISel-llvm/build/bin/clang++ -O3 -S -emit-llvm -funroll-loops -mllvm -force-vector-interleave=4 -fvectorize -std=c++14                -m64 -c -o hfield.ll -DSPEC -DSPEC_CPU -DNDEBUG -Ifrontend -Ibase -I. -Ispec_qsort -DSPEC_AUTO_SUPPRESS_OPENMP         -DSPEC_LP64  hfield.cpp
/home/yjs/workspace/GPUISel-llvm/build/bin/clang++ -O3 -S -emit-llvm -funroll-loops -mllvm -force-vector-interleave=4 -fvectorize -std=c++14                -m64 -c -o histogra.ll -DSPEC -DSPEC_CPU -DNDEBUG -Ifrontend -Ibase -I. -Ispec_qsort -DSPEC_AUTO_SUPPRESS_OPENMP         -DSPEC_LP64  histogra.cpp
/home/yjs/workspace/GPUISel-llvm/build/bin/clang++ -O3 -S -emit-llvm -funroll-loops -mllvm -force-vector-interleave=4 -fvectorize -std=c++14                -m64 -c -o iff.ll -DSPEC -DSPEC_CPU -DNDEBUG -Ifrontend -Ibase -I. -Ispec_qsort -DSPEC_AUTO_SUPPRESS_OPENMP         -DSPEC_LP64  iff.cpp
/home/yjs/workspace/GPUISel-llvm/build/bin/clang++ -O3 -S -emit-llvm -funroll-loops -mllvm -force-vector-interleave=4 -fvectorize -std=c++14                -m64 -c -o image.ll -DSPEC -DSPEC_CPU -DNDEBUG -Ifrontend -Ibase -I. -Ispec_qsort -DSPEC_AUTO_SUPPRESS_OPENMP         -DSPEC_LP64  image.cpp
/home/yjs/workspace/GPUISel-llvm/build/bin/clang++ -O3 -S -emit-llvm -funroll-loops -mllvm -force-vector-interleave=4 -fvectorize -std=c++14                -m64 -c -o interior.ll -DSPEC -DSPEC_CPU -DNDEBUG -Ifrontend -Ibase -I. -Ispec_qsort -DSPEC_AUTO_SUPPRESS_OPENMP         -DSPEC_LP64  interior.cpp
/home/yjs/workspace/GPUISel-llvm/build/bin/clang++ -O3 -S -emit-llvm -funroll-loops -mllvm -force-vector-interleave=4 -fvectorize -std=c++14                -m64 -c -o isosurf.ll -DSPEC -DSPEC_CPU -DNDEBUG -Ifrontend -Ibase -I. -Ispec_qsort -DSPEC_AUTO_SUPPRESS_OPENMP         -DSPEC_LP64  isosurf.cpp
/home/yjs/workspace/GPUISel-llvm/build/bin/clang++ -O3 -S -emit-llvm -funroll-loops -mllvm -force-vector-interleave=4 -fvectorize -std=c++14                -m64 -c -o lathe.ll -DSPEC -DSPEC_CPU -DNDEBUG -Ifrontend -Ibase -I. -Ispec_qsort -DSPEC_AUTO_SUPPRESS_OPENMP         -DSPEC_LP64  lathe.cpp
/home/yjs/workspace/GPUISel-llvm/build/bin/clang++ -O3 -S -emit-llvm -funroll-loops -mllvm -force-vector-interleave=4 -fvectorize -std=c++14                -m64 -c -o lbuffer.ll -DSPEC -DSPEC_CPU -DNDEBUG -Ifrontend -Ibase -I. -Ispec_qsort -DSPEC_AUTO_SUPPRESS_OPENMP         -DSPEC_LP64  lbuffer.cpp
/home/yjs/workspace/GPUISel-llvm/build/bin/clang++ -O3 -S -emit-llvm -funroll-loops -mllvm -force-vector-interleave=4 -fvectorize -std=c++14                -m64 -c -o lightgrp.ll -DSPEC -DSPEC_CPU -DNDEBUG -Ifrontend -Ibase -I. -Ispec_qsort -DSPEC_AUTO_SUPPRESS_OPENMP         -DSPEC_LP64  lightgrp.cpp
/home/yjs/workspace/GPUISel-llvm/build/bin/clang++ -O3 -S -emit-llvm -funroll-loops -mllvm -force-vector-interleave=4 -fvectorize -std=c++14                -m64 -c -o lighting.ll -DSPEC -DSPEC_CPU -DNDEBUG -Ifrontend -Ibase -I. -Ispec_qsort -DSPEC_AUTO_SUPPRESS_OPENMP         -DSPEC_LP64  lighting.cpp
/home/yjs/workspace/GPUISel-llvm/build/bin/clang++ -O3 -S -emit-llvm -funroll-loops -mllvm -force-vector-interleave=4 -fvectorize -std=c++14                -m64 -c -o mathutil.ll -DSPEC -DSPEC_CPU -DNDEBUG -Ifrontend -Ibase -I. -Ispec_qsort -DSPEC_AUTO_SUPPRESS_OPENMP         -DSPEC_LP64  mathutil.cpp
/home/yjs/workspace/GPUISel-llvm/build/bin/clang++ -O3 -S -emit-llvm -funroll-loops -mllvm -force-vector-interleave=4 -fvectorize -std=c++14                -m64 -c -o matrices.ll -DSPEC -DSPEC_CPU -DNDEBUG -Ifrontend -Ibase -I. -Ispec_qsort -DSPEC_AUTO_SUPPRESS_OPENMP         -DSPEC_LP64  matrices.cpp
/home/yjs/workspace/GPUISel-llvm/build/bin/clang++ -O3 -S -emit-llvm -funroll-loops -mllvm -force-vector-interleave=4 -fvectorize -std=c++14                -m64 -c -o media.ll -DSPEC -DSPEC_CPU -DNDEBUG -Ifrontend -Ibase -I. -Ispec_qsort -DSPEC_AUTO_SUPPRESS_OPENMP         -DSPEC_LP64  media.cpp
/home/yjs/workspace/GPUISel-llvm/build/bin/clang++ -O3 -S -emit-llvm -funroll-loops -mllvm -force-vector-interleave=4 -fvectorize -std=c++14                -m64 -c -o mesh.ll -DSPEC -DSPEC_CPU -DNDEBUG -Ifrontend -Ibase -I. -Ispec_qsort -DSPEC_AUTO_SUPPRESS_OPENMP         -DSPEC_LP64  mesh.cpp
/home/yjs/workspace/GPUISel-llvm/build/bin/clang++ -O3 -S -emit-llvm -funroll-loops -mllvm -force-vector-interleave=4 -fvectorize -std=c++14                -m64 -c -o normal.ll -DSPEC -DSPEC_CPU -DNDEBUG -Ifrontend -Ibase -I. -Ispec_qsort -DSPEC_AUTO_SUPPRESS_OPENMP         -DSPEC_LP64  normal.cpp
/home/yjs/workspace/GPUISel-llvm/build/bin/clang++ -O3 -S -emit-llvm -funroll-loops -mllvm -force-vector-interleave=4 -fvectorize -std=c++14                -m64 -c -o objects.ll -DSPEC -DSPEC_CPU -DNDEBUG -Ifrontend -Ibase -I. -Ispec_qsort -DSPEC_AUTO_SUPPRESS_OPENMP         -DSPEC_LP64  objects.cpp
/home/yjs/workspace/GPUISel-llvm/build/bin/clang++ -O3 -S -emit-llvm -funroll-loops -mllvm -force-vector-interleave=4 -fvectorize -std=c++14                -m64 -c -o octree.ll -DSPEC -DSPEC_CPU -DNDEBUG -Ifrontend -Ibase -I. -Ispec_qsort -DSPEC_AUTO_SUPPRESS_OPENMP         -DSPEC_LP64  octree.cpp
/home/yjs/workspace/GPUISel-llvm/build/bin/clang++ -O3 -S -emit-llvm -funroll-loops -mllvm -force-vector-interleave=4 -fvectorize -std=c++14                -m64 -c -o optout.ll -DSPEC -DSPEC_CPU -DNDEBUG -Ifrontend -Ibase -I. -Ispec_qsort -DSPEC_AUTO_SUPPRESS_OPENMP         -DSPEC_LP64  optout.cpp
/home/yjs/workspace/GPUISel-llvm/build/bin/clang++ -O3 -S -emit-llvm -funroll-loops -mllvm -force-vector-interleave=4 -fvectorize -std=c++14                -m64 -c -o parse.ll -DSPEC -DSPEC_CPU -DNDEBUG -Ifrontend -Ibase -I. -Ispec_qsort -DSPEC_AUTO_SUPPRESS_OPENMP         -DSPEC_LP64  parse.cpp
/home/yjs/workspace/GPUISel-llvm/build/bin/clang++ -O3 -S -emit-llvm -funroll-loops -mllvm -force-vector-interleave=4 -fvectorize -std=c++14                -m64 -c -o parsestr.ll -DSPEC -DSPEC_CPU -DNDEBUG -Ifrontend -Ibase -I. -Ispec_qsort -DSPEC_AUTO_SUPPRESS_OPENMP         -DSPEC_LP64  parsestr.cpp
/home/yjs/workspace/GPUISel-llvm/build/bin/clang++ -O3 -S -emit-llvm -funroll-loops -mllvm -force-vector-interleave=4 -fvectorize -std=c++14                -m64 -c -o parstxtr.ll -DSPEC -DSPEC_CPU -DNDEBUG -Ifrontend -Ibase -I. -Ispec_qsort -DSPEC_AUTO_SUPPRESS_OPENMP         -DSPEC_LP64  parstxtr.cpp
/home/yjs/workspace/GPUISel-llvm/build/bin/clang++ -O3 -S -emit-llvm -funroll-loops -mllvm -force-vector-interleave=4 -fvectorize -std=c++14                -m64 -c -o pattern.ll -DSPEC -DSPEC_CPU -DNDEBUG -Ifrontend -Ibase -I. -Ispec_qsort -DSPEC_AUTO_SUPPRESS_OPENMP         -DSPEC_LP64  pattern.cpp
/home/yjs/workspace/GPUISel-llvm/build/bin/clang++ -O3 -S -emit-llvm -funroll-loops -mllvm -force-vector-interleave=4 -fvectorize -std=c++14                -m64 -c -o pgm.ll -DSPEC -DSPEC_CPU -DNDEBUG -Ifrontend -Ibase -I. -Ispec_qsort -DSPEC_AUTO_SUPPRESS_OPENMP         -DSPEC_LP64  pgm.cpp
/home/yjs/workspace/GPUISel-llvm/build/bin/clang++ -O3 -S -emit-llvm -funroll-loops -mllvm -force-vector-interleave=4 -fvectorize -std=c++14                -m64 -c -o photons.ll -DSPEC -DSPEC_CPU -DNDEBUG -Ifrontend -Ibase -I. -Ispec_qsort -DSPEC_AUTO_SUPPRESS_OPENMP         -DSPEC_LP64  photons.cpp
/home/yjs/workspace/GPUISel-llvm/build/bin/clang++ -O3 -S -emit-llvm -funroll-loops -mllvm -force-vector-interleave=4 -fvectorize -std=c++14                -m64 -c -o pigment.ll -DSPEC -DSPEC_CPU -DNDEBUG -Ifrontend -Ibase -I. -Ispec_qsort -DSPEC_AUTO_SUPPRESS_OPENMP         -DSPEC_LP64  pigment.cpp
/home/yjs/workspace/GPUISel-llvm/build/bin/clang++ -O3 -S -emit-llvm -funroll-loops -mllvm -force-vector-interleave=4 -fvectorize -std=c++14                -m64 -c -o planes.ll -DSPEC -DSPEC_CPU -DNDEBUG -Ifrontend -Ibase -I. -Ispec_qsort -DSPEC_AUTO_SUPPRESS_OPENMP         -DSPEC_LP64  planes.cpp
/home/yjs/workspace/GPUISel-llvm/build/bin/clang++ -O3 -S -emit-llvm -funroll-loops -mllvm -force-vector-interleave=4 -fvectorize -std=c++14                -m64 -c -o point.ll -DSPEC -DSPEC_CPU -DNDEBUG -Ifrontend -Ibase -I. -Ispec_qsort -DSPEC_AUTO_SUPPRESS_OPENMP         -DSPEC_LP64  point.cpp
/home/yjs/workspace/GPUISel-llvm/build/bin/clang++ -O3 -S -emit-llvm -funroll-loops -mllvm -force-vector-interleave=4 -fvectorize -std=c++14                -m64 -c -o poly.ll -DSPEC -DSPEC_CPU -DNDEBUG -Ifrontend -Ibase -I. -Ispec_qsort -DSPEC_AUTO_SUPPRESS_OPENMP         -DSPEC_LP64  poly.cpp
/home/yjs/workspace/GPUISel-llvm/build/bin/clang++ -O3 -S -emit-llvm -funroll-loops -mllvm -force-vector-interleave=4 -fvectorize -std=c++14                -m64 -c -o polygon.ll -DSPEC -DSPEC_CPU -DNDEBUG -Ifrontend -Ibase -I. -Ispec_qsort -DSPEC_AUTO_SUPPRESS_OPENMP         -DSPEC_LP64  polygon.cpp
/home/yjs/workspace/GPUISel-llvm/build/bin/clang++ -O3 -S -emit-llvm -funroll-loops -mllvm -force-vector-interleave=4 -fvectorize -std=c++14                -m64 -c -o polysolv.ll -DSPEC -DSPEC_CPU -DNDEBUG -Ifrontend -Ibase -I. -Ispec_qsort -DSPEC_AUTO_SUPPRESS_OPENMP         -DSPEC_LP64  polysolv.cpp
/home/yjs/workspace/GPUISel-llvm/build/bin/clang++ -O3 -S -emit-llvm -funroll-loops -mllvm -force-vector-interleave=4 -fvectorize -std=c++14                -m64 -c -o povmsend.ll -DSPEC -DSPEC_CPU -DNDEBUG -Ifrontend -Ibase -I. -Ispec_qsort -DSPEC_AUTO_SUPPRESS_OPENMP         -DSPEC_LP64  povmsend.cpp
/home/yjs/workspace/GPUISel-llvm/build/bin/clang++ -O3 -S -emit-llvm -funroll-loops -mllvm -force-vector-interleave=4 -fvectorize -std=c++14                -m64 -c -o povmsrec.ll -DSPEC -DSPEC_CPU -DNDEBUG -Ifrontend -Ibase -I. -Ispec_qsort -DSPEC_AUTO_SUPPRESS_OPENMP         -DSPEC_LP64  povmsrec.cpp
/home/yjs/workspace/GPUISel-llvm/build/bin/clang++ -O3 -S -emit-llvm -funroll-loops -mllvm -force-vector-interleave=4 -fvectorize -std=c++14                -m64 -c -o povray.ll -DSPEC -DSPEC_CPU -DNDEBUG -Ifrontend -Ibase -I. -Ispec_qsort -DSPEC_AUTO_SUPPRESS_OPENMP         -DSPEC_LP64  povray.cpp
/home/yjs/workspace/GPUISel-llvm/build/bin/clang++ -O3 -S -emit-llvm -funroll-loops -mllvm -force-vector-interleave=4 -fvectorize -std=c++14                -m64 -c -o pov_mem.ll -DSPEC -DSPEC_CPU -DNDEBUG -Ifrontend -Ibase -I. -Ispec_qsort -DSPEC_AUTO_SUPPRESS_OPENMP         -DSPEC_LP64  pov_mem.cpp
/home/yjs/workspace/GPUISel-llvm/build/bin/clang++ -O3 -S -emit-llvm -funroll-loops -mllvm -force-vector-interleave=4 -fvectorize -std=c++14                -m64 -c -o pov_util.ll -DSPEC -DSPEC_CPU -DNDEBUG -Ifrontend -Ibase -I. -Ispec_qsort -DSPEC_AUTO_SUPPRESS_OPENMP         -DSPEC_LP64  pov_util.cpp
/home/yjs/workspace/GPUISel-llvm/build/bin/clang++ -O3 -S -emit-llvm -funroll-loops -mllvm -force-vector-interleave=4 -fvectorize -std=c++14                -m64 -c -o ppm.ll -DSPEC -DSPEC_CPU -DNDEBUG -Ifrontend -Ibase -I. -Ispec_qsort -DSPEC_AUTO_SUPPRESS_OPENMP         -DSPEC_LP64  ppm.cpp
/home/yjs/workspace/GPUISel-llvm/build/bin/clang++ -O3 -S -emit-llvm -funroll-loops -mllvm -force-vector-interleave=4 -fvectorize -std=c++14                -m64 -c -o prism.ll -DSPEC -DSPEC_CPU -DNDEBUG -Ifrontend -Ibase -I. -Ispec_qsort -DSPEC_AUTO_SUPPRESS_OPENMP         -DSPEC_LP64  prism.cpp
/home/yjs/workspace/GPUISel-llvm/build/bin/clang++ -O3 -S -emit-llvm -funroll-loops -mllvm -force-vector-interleave=4 -fvectorize -std=c++14                -m64 -c -o quadrics.ll -DSPEC -DSPEC_CPU -DNDEBUG -Ifrontend -Ibase -I. -Ispec_qsort -DSPEC_AUTO_SUPPRESS_OPENMP         -DSPEC_LP64  quadrics.cpp
/home/yjs/workspace/GPUISel-llvm/build/bin/clang++ -O3 -S -emit-llvm -funroll-loops -mllvm -force-vector-interleave=4 -fvectorize -std=c++14                -m64 -c -o quatern.ll -DSPEC -DSPEC_CPU -DNDEBUG -Ifrontend -Ibase -I. -Ispec_qsort -DSPEC_AUTO_SUPPRESS_OPENMP         -DSPEC_LP64  quatern.cpp
/home/yjs/workspace/GPUISel-llvm/build/bin/clang++ -O3 -S -emit-llvm -funroll-loops -mllvm -force-vector-interleave=4 -fvectorize -std=c++14                -m64 -c -o radiosit.ll -DSPEC -DSPEC_CPU -DNDEBUG -Ifrontend -Ibase -I. -Ispec_qsort -DSPEC_AUTO_SUPPRESS_OPENMP         -DSPEC_LP64  radiosit.cpp
/home/yjs/workspace/GPUISel-llvm/build/bin/clang++ -O3 -S -emit-llvm -funroll-loops -mllvm -force-vector-interleave=4 -fvectorize -std=c++14                -m64 -c -o rad_data.ll -DSPEC -DSPEC_CPU -DNDEBUG -Ifrontend -Ibase -I. -Ispec_qsort -DSPEC_AUTO_SUPPRESS_OPENMP         -DSPEC_LP64  rad_data.cpp
/home/yjs/workspace/GPUISel-llvm/build/bin/clang++ -O3 -S -emit-llvm -funroll-loops -mllvm -force-vector-interleave=4 -fvectorize -std=c++14                -m64 -c -o ray.ll -DSPEC -DSPEC_CPU -DNDEBUG -Ifrontend -Ibase -I. -Ispec_qsort -DSPEC_AUTO_SUPPRESS_OPENMP         -DSPEC_LP64  ray.cpp
/home/yjs/workspace/GPUISel-llvm/build/bin/clang++ -O3 -S -emit-llvm -funroll-loops -mllvm -force-vector-interleave=4 -fvectorize -std=c++14                -m64 -c -o rendctrl.ll -DSPEC -DSPEC_CPU -DNDEBUG -Ifrontend -Ibase -I. -Ispec_qsort -DSPEC_AUTO_SUPPRESS_OPENMP         -DSPEC_LP64  rendctrl.cpp
/home/yjs/workspace/GPUISel-llvm/build/bin/clang++ -O3 -S -emit-llvm -funroll-loops -mllvm -force-vector-interleave=4 -fvectorize -std=c++14                -m64 -c -o render.ll -DSPEC -DSPEC_CPU -DNDEBUG -Ifrontend -Ibase -I. -Ispec_qsort -DSPEC_AUTO_SUPPRESS_OPENMP         -DSPEC_LP64  render.cpp
/home/yjs/workspace/GPUISel-llvm/build/bin/clang++ -O3 -S -emit-llvm -funroll-loops -mllvm -force-vector-interleave=4 -fvectorize -std=c++14                -m64 -c -o renderio.ll -DSPEC -DSPEC_CPU -DNDEBUG -Ifrontend -Ibase -I. -Ispec_qsort -DSPEC_AUTO_SUPPRESS_OPENMP         -DSPEC_LP64  renderio.cpp
/home/yjs/workspace/GPUISel-llvm/build/bin/clang++ -O3 -S -emit-llvm -funroll-loops -mllvm -force-vector-interleave=4 -fvectorize -std=c++14                -m64 -c -o reswords.ll -DSPEC -DSPEC_CPU -DNDEBUG -Ifrontend -Ibase -I. -Ispec_qsort -DSPEC_AUTO_SUPPRESS_OPENMP         -DSPEC_LP64  reswords.cpp
/home/yjs/workspace/GPUISel-llvm/build/bin/clang++ -O3 -S -emit-llvm -funroll-loops -mllvm -force-vector-interleave=4 -fvectorize -std=c++14                -m64 -c -o sor.ll -DSPEC -DSPEC_CPU -DNDEBUG -Ifrontend -Ibase -I. -Ispec_qsort -DSPEC_AUTO_SUPPRESS_OPENMP         -DSPEC_LP64  sor.cpp
/home/yjs/workspace/GPUISel-llvm/build/bin/clang++ -O3 -S -emit-llvm -funroll-loops -mllvm -force-vector-interleave=4 -fvectorize -std=c++14                -m64 -c -o spheres.ll -DSPEC -DSPEC_CPU -DNDEBUG -Ifrontend -Ibase -I. -Ispec_qsort -DSPEC_AUTO_SUPPRESS_OPENMP         -DSPEC_LP64  spheres.cpp
/home/yjs/workspace/GPUISel-llvm/build/bin/clang++ -O3 -S -emit-llvm -funroll-loops -mllvm -force-vector-interleave=4 -fvectorize -std=c++14                -m64 -c -o sphsweep.ll -DSPEC -DSPEC_CPU -DNDEBUG -Ifrontend -Ibase -I. -Ispec_qsort -DSPEC_AUTO_SUPPRESS_OPENMP         -DSPEC_LP64  sphsweep.cpp
/home/yjs/workspace/GPUISel-llvm/build/bin/clang++ -O3 -S -emit-llvm -funroll-loops -mllvm -force-vector-interleave=4 -fvectorize -std=c++14                -m64 -c -o splines.ll -DSPEC -DSPEC_CPU -DNDEBUG -Ifrontend -Ibase -I. -Ispec_qsort -DSPEC_AUTO_SUPPRESS_OPENMP         -DSPEC_LP64  splines.cpp
/home/yjs/workspace/GPUISel-llvm/build/bin/clang++ -O3 -S -emit-llvm -funroll-loops -mllvm -force-vector-interleave=4 -fvectorize -std=c++14                -m64 -c -o statspov.ll -DSPEC -DSPEC_CPU -DNDEBUG -Ifrontend -Ibase -I. -Ispec_qsort -DSPEC_AUTO_SUPPRESS_OPENMP         -DSPEC_LP64  statspov.cpp
/home/yjs/workspace/GPUISel-llvm/build/bin/clang++ -O3 -S -emit-llvm -funroll-loops -mllvm -force-vector-interleave=4 -fvectorize -std=c++14                -m64 -c -o super.ll -DSPEC -DSPEC_CPU -DNDEBUG -Ifrontend -Ibase -I. -Ispec_qsort -DSPEC_AUTO_SUPPRESS_OPENMP         -DSPEC_LP64  super.cpp
/home/yjs/workspace/GPUISel-llvm/build/bin/clang++ -O3 -S -emit-llvm -funroll-loops -mllvm -force-vector-interleave=4 -fvectorize -std=c++14                -m64 -c -o targa.ll -DSPEC -DSPEC_CPU -DNDEBUG -Ifrontend -Ibase -I. -Ispec_qsort -DSPEC_AUTO_SUPPRESS_OPENMP         -DSPEC_LP64  targa.cpp
/home/yjs/workspace/GPUISel-llvm/build/bin/clang++ -O3 -S -emit-llvm -funroll-loops -mllvm -force-vector-interleave=4 -fvectorize -std=c++14                -m64 -c -o texture.ll -DSPEC -DSPEC_CPU -DNDEBUG -Ifrontend -Ibase -I. -Ispec_qsort -DSPEC_AUTO_SUPPRESS_OPENMP         -DSPEC_LP64  texture.cpp
/home/yjs/workspace/GPUISel-llvm/build/bin/clang++ -O3 -S -emit-llvm -funroll-loops -mllvm -force-vector-interleave=4 -fvectorize -std=c++14                -m64 -c -o tokenize.ll -DSPEC -DSPEC_CPU -DNDEBUG -Ifrontend -Ibase -I. -Ispec_qsort -DSPEC_AUTO_SUPPRESS_OPENMP         -DSPEC_LP64  tokenize.cpp
/home/yjs/workspace/GPUISel-llvm/build/bin/clang++ -O3 -S -emit-llvm -funroll-loops -mllvm -force-vector-interleave=4 -fvectorize -std=c++14                -m64 -c -o torus.ll -DSPEC -DSPEC_CPU -DNDEBUG -Ifrontend -Ibase -I. -Ispec_qsort -DSPEC_AUTO_SUPPRESS_OPENMP         -DSPEC_LP64  torus.cpp
/home/yjs/workspace/GPUISel-llvm/build/bin/clang++ -O3 -S -emit-llvm -funroll-loops -mllvm -force-vector-interleave=4 -fvectorize -std=c++14                -m64 -c -o triangle.ll -DSPEC -DSPEC_CPU -DNDEBUG -Ifrontend -Ibase -I. -Ispec_qsort -DSPEC_AUTO_SUPPRESS_OPENMP         -DSPEC_LP64  triangle.cpp
/home/yjs/workspace/GPUISel-llvm/build/bin/clang++ -O3 -S -emit-llvm -funroll-loops -mllvm -force-vector-interleave=4 -fvectorize -std=c++14                -m64 -c -o truetype.ll -DSPEC -DSPEC_CPU -DNDEBUG -Ifrontend -Ibase -I. -Ispec_qsort -DSPEC_AUTO_SUPPRESS_OPENMP         -DSPEC_LP64  truetype.cpp
/home/yjs/workspace/GPUISel-llvm/build/bin/clang++ -O3 -S -emit-llvm -funroll-loops -mllvm -force-vector-interleave=4 -fvectorize -std=c++14                -m64 -c -o txttest.ll -DSPEC -DSPEC_CPU -DNDEBUG -Ifrontend -Ibase -I. -Ispec_qsort -DSPEC_AUTO_SUPPRESS_OPENMP         -DSPEC_LP64  txttest.cpp
/home/yjs/workspace/GPUISel-llvm/build/bin/clang++ -O3 -S -emit-llvm -funroll-loops -mllvm -force-vector-interleave=4 -fvectorize -std=c++14                -m64 -c -o userdisp.ll -DSPEC -DSPEC_CPU -DNDEBUG -Ifrontend -Ibase -I. -Ispec_qsort -DSPEC_AUTO_SUPPRESS_OPENMP         -DSPEC_LP64  userdisp.cpp
/home/yjs/workspace/GPUISel-llvm/build/bin/clang++ -O3 -S -emit-llvm -funroll-loops -mllvm -force-vector-interleave=4 -fvectorize -std=c++14                -m64 -c -o userio.ll -DSPEC -DSPEC_CPU -DNDEBUG -Ifrontend -Ibase -I. -Ispec_qsort -DSPEC_AUTO_SUPPRESS_OPENMP         -DSPEC_LP64  userio.cpp
/home/yjs/workspace/GPUISel-llvm/build/bin/clang++ -O3 -S -emit-llvm -funroll-loops -mllvm -force-vector-interleave=4 -fvectorize -std=c++14                -m64 -c -o vbuffer.ll -DSPEC -DSPEC_CPU -DNDEBUG -Ifrontend -Ibase -I. -Ispec_qsort -DSPEC_AUTO_SUPPRESS_OPENMP         -DSPEC_LP64  vbuffer.cpp
/home/yjs/workspace/GPUISel-llvm/build/bin/clang++ -O3 -S -emit-llvm -funroll-loops -mllvm -force-vector-interleave=4 -fvectorize -std=c++14                -m64 -c -o vlbuffer.ll -DSPEC -DSPEC_CPU -DNDEBUG -Ifrontend -Ibase -I. -Ispec_qsort -DSPEC_AUTO_SUPPRESS_OPENMP         -DSPEC_LP64  vlbuffer.cpp
/home/yjs/workspace/GPUISel-llvm/build/bin/clang++ -O3 -S -emit-llvm -funroll-loops -mllvm -force-vector-interleave=4 -fvectorize -std=c++14                -m64 -c -o warps.ll -DSPEC -DSPEC_CPU -DNDEBUG -Ifrontend -Ibase -I. -Ispec_qsort -DSPEC_AUTO_SUPPRESS_OPENMP         -DSPEC_LP64  warps.cpp
/home/yjs/workspace/GPUISel-llvm/build/bin/clang++ -O3 -S -emit-llvm -funroll-loops -mllvm -force-vector-interleave=4 -fvectorize -std=c++14                -m64 -c -o base/fileinputoutput.ll -DSPEC -DSPEC_CPU -DNDEBUG -Ifrontend -Ibase -I. -Ispec_qsort -DSPEC_AUTO_SUPPRESS_OPENMP         -DSPEC_LP64  base/fileinputoutput.cpp
/home/yjs/workspace/GPUISel-llvm/build/bin/clang++ -O3 -S -emit-llvm -funroll-loops -mllvm -force-vector-interleave=4 -fvectorize -std=c++14                -m64 -c -o base/povms.ll -DSPEC -DSPEC_CPU -DNDEBUG -Ifrontend -Ibase -I. -Ispec_qsort -DSPEC_AUTO_SUPPRESS_OPENMP         -DSPEC_LP64  base/povms.cpp
/home/yjs/workspace/GPUISel-llvm/build/bin/clang++ -O3 -S -emit-llvm -funroll-loops -mllvm -force-vector-interleave=4 -fvectorize -std=c++14                -m64 -c -o base/povmscpp.ll -DSPEC -DSPEC_CPU -DNDEBUG -Ifrontend -Ibase -I. -Ispec_qsort -DSPEC_AUTO_SUPPRESS_OPENMP         -DSPEC_LP64  base/povmscpp.cpp
/home/yjs/workspace/GPUISel-llvm/build/bin/clang++ -O3 -S -emit-llvm -funroll-loops -mllvm -force-vector-interleave=4 -fvectorize -std=c++14                -m64 -c -o base/processoptions.ll -DSPEC -DSPEC_CPU -DNDEBUG -Ifrontend -Ibase -I. -Ispec_qsort -DSPEC_AUTO_SUPPRESS_OPENMP         -DSPEC_LP64  base/processoptions.cpp
/home/yjs/workspace/GPUISel-llvm/build/bin/clang++ -O3 -S -emit-llvm -funroll-loops -mllvm -force-vector-interleave=4 -fvectorize -std=c++14                -m64 -c -o base/stringutilities.ll -DSPEC -DSPEC_CPU -DNDEBUG -Ifrontend -Ibase -I. -Ispec_qsort -DSPEC_AUTO_SUPPRESS_OPENMP         -DSPEC_LP64  base/stringutilities.cpp
/home/yjs/workspace/GPUISel-llvm/build/bin/clang++ -O3 -S -emit-llvm -funroll-loops -mllvm -force-vector-interleave=4 -fvectorize -std=c++14                -m64 -c -o base/textstream.ll -DSPEC -DSPEC_CPU -DNDEBUG -Ifrontend -Ibase -I. -Ispec_qsort -DSPEC_AUTO_SUPPRESS_OPENMP         -DSPEC_LP64  base/textstream.cpp
/home/yjs/workspace/GPUISel-llvm/build/bin/clang++ -O3 -S -emit-llvm -funroll-loops -mllvm -force-vector-interleave=4 -fvectorize -std=c++14                -m64 -c -o base/textstreambuffer.ll -DSPEC -DSPEC_CPU -DNDEBUG -Ifrontend -Ibase -I. -Ispec_qsort -DSPEC_AUTO_SUPPRESS_OPENMP         -DSPEC_LP64  base/textstreambuffer.cpp
/home/yjs/workspace/GPUISel-llvm/build/bin/clang++ -O3 -S -emit-llvm -funroll-loops -mllvm -force-vector-interleave=4 -fvectorize -std=c++14                -m64 -c -o frontend/defaultplatformbase.ll -DSPEC -DSPEC_CPU -DNDEBUG -Ifrontend -Ibase -I. -Ispec_qsort -DSPEC_AUTO_SUPPRESS_OPENMP         -DSPEC_LP64  frontend/defaultplatformbase.cpp
/home/yjs/workspace/GPUISel-llvm/build/bin/clang++ -O3 -S -emit-llvm -funroll-loops -mllvm -force-vector-interleave=4 -fvectorize -std=c++14                -m64 -c -o frontend/defaultrenderfrontend.ll -DSPEC -DSPEC_CPU -DNDEBUG -Ifrontend -Ibase -I. -Ispec_qsort -DSPEC_AUTO_SUPPRESS_OPENMP         -DSPEC_LP64  frontend/defaultrenderfrontend.cpp
/home/yjs/workspace/GPUISel-llvm/build/bin/clang++ -O3 -S -emit-llvm -funroll-loops -mllvm -force-vector-interleave=4 -fvectorize -std=c++14                -m64 -c -o frontend/messageoutput.ll -DSPEC -DSPEC_CPU -DNDEBUG -Ifrontend -Ibase -I. -Ispec_qsort -DSPEC_AUTO_SUPPRESS_OPENMP         -DSPEC_LP64  frontend/messageoutput.cpp
/home/yjs/workspace/GPUISel-llvm/build/bin/clang++ -O3 -S -emit-llvm -funroll-loops -mllvm -force-vector-interleave=4 -fvectorize -std=c++14                -m64 -c -o frontend/processrenderoptions.ll -DSPEC -DSPEC_CPU -DNDEBUG -Ifrontend -Ibase -I. -Ispec_qsort -DSPEC_AUTO_SUPPRESS_OPENMP         -DSPEC_LP64  frontend/processrenderoptions.cpp
/home/yjs/workspace/GPUISel-llvm/build/bin/clang++ -O3 -S -emit-llvm -funroll-loops -mllvm -force-vector-interleave=4 -fvectorize -std=c++14                -m64 -c -o frontend/renderfrontend.ll -DSPEC -DSPEC_CPU -DNDEBUG -Ifrontend -Ibase -I. -Ispec_qsort -DSPEC_AUTO_SUPPRESS_OPENMP         -DSPEC_LP64  frontend/renderfrontend.cpp
/home/yjs/workspace/GPUISel-llvm/build/bin/clang -O3 -S -emit-llvm -funroll-loops -mllvm -force-vector-interleave=4 -fvectorize -std=c++14     -std=c99   -m64 -c -o spec_qsort/spec_qsort.ll -DSPEC -DSPEC_CPU -DNDEBUG -Ifrontend -Ibase -I. -Ispec_qsort -DSPEC_AUTO_SUPPRESS_OPENMP               -DSPEC_LP64  spec_qsort/spec_qsort.c
